### ISSUE TITLE
No Stream Support?

### ISSUE THREAD

**Issue by CodeMan99** [kevva/decompress-unzip#16]
Of the default `decompress` plugins, this seems to be the only one that doesn't seem to support streamed input.

Is there a particular reason why streaming is not supported for unzip? There is already a dependency on `get-stream`, so it seems reasonable to just put that in front of the `yauzl` call.

**Comment by kevva** [comment]
Yes, I've explained why in https://github.com/kevva/decompress/issues/29#issuecomment-302930991. Until we've a better alternative to `yauzl`, I think we're stuck with the Promise API.

**Comment by CodeMan99** [comment]
Ok. So just for the sake of future readers. You are saying that you agree with the author of `yauzl` and that the library shouldn't buffer the stream contents?

**Comment by kevva** [comment]
I'd like for this module to support streams, but since `yauzl` doesn't, and since it's the best alternative out there currently, I don't see how we can accomplish it right now.

**Comment by CodeMan99** [comment]
> I don't see how we can accomplish it right now.

You mean without using `getStream.buffer`?

I mean, if you are ok with buffering internally in the plugin, it would be very easy to do.

**Comment by kevva** [comment]
It's not super pure, but sure, we could do it. PR welcome.

**Comment by CodeMan99** [comment]
@kevva Closing this again as the PR is now closed.

**Comment by kevva** [comment]
Apparently I changed my mind since. But yeah, not a big fan of supporting it if we're going to buffer it anyway.
