### ISSUE TITLE
Wrong stat

### ISSUE THREAD

**Issue by TrySound** [kevva/decompress-unzip#6]
```js
var Decompress = require('decompress'),
	unzip = require('decompress-unzip');

new Decompress()
	.src('master.zip')
	.use(unzip({ strip: 1 }))
	.run(function (err, files) {
		files.forEach(function (file) {
			console.log(file.stat.isFile(), file.path);
		});
	});

```

[master.zip here](https://github.com/artem-malko/tars-handlebars/archive/master.zip)

**Comment by kevva** [comment]
@TrySound, try `3.2.1` and see if it works now :).

**Comment by TrySound** [comment]
That's better, but is there way to make `file.stat.isFIle()` and `file.stat.isDirectory()`

**Comment by shinnn** [comment]
@TrySound Use `file.isBuffer()` and `file.isNull()` instead.

**Comment by kevva** [comment]
@shinnn, do we need the `stat.isDirectory()` check or could we just rely on the path ending with `/`? Or does node set `stat.isDirectory()` automatically if it detects the correct mode? Else it does nothing for us because `yauzl` doesn't have `.isDirectory()`.

**Comment by TrySound** [comment]
Rely on `/` set type by [stat-mode](https://github.com/TooTallNate/stat-mode)

**Comment by shinnn** [comment]
> do we need the `stat.isDirectory()` check or could we just rely on the path ending with `/`?

I think `stat.isDirectory()` is not needed anymore.

> does node set `stat.isDirectory()` automatically if it detects the correct mode?

Yes.

```js
// manually create stat object
var stat = new fs.Stats();

stat.isDirectory(); //=> false

// simulate directory mode
stat.mode = 16877;

stat.isDirectory(); //=> true
```

**Comment by TrySound** [comment]
Node can't automatically sets mode of vinyl file. No need to simulate. Give us correct ways to use it.
I want to call file.isDirectory() and gets correct answer. For this add small `stats-mode` to your dependencies, please.

**Comment by kevva** [comment]
@TrySound, look at the example above. We are passing on the stats object to the vinyl file as seen [here](https://github.com/kevva/decompress-unzip/blob/master/index.js#L67) and [here](https://github.com/kevva/decompress-unzip/blob/master/index.js#L92).

**Comment by TrySound** [comment]
@kevva I see, but stat.mode is not correct

**Comment by shinnn** [comment]
We need to set default file (or directory) mode in current OS to `stat` object, when [this line](https://github.com/kevva/decompress-unzip/blob/master/index.js#L54) fails to detect actual file mode.

**Comment by TrySound** [comment]
@shinnn I don't know why it's doesn't work. file.stat.isFile and file.stat.isDirectory give wrong values

**Comment by kevva** [comment]
@shinnn, we could just set 755 for directories and 644 for files and then set `isFile()` and `isDirectory()` manually. It's ugly, but that'll do it I think.

**Comment by TrySound** [comment]
@kevva [stat-mode](https://github.com/TooTallNate/stat-mode) is more elegant

**Comment by kevva** [comment]
@TrySound, thing is, if we don't have a mode that's not useful.

**Comment by TrySound** [comment]
@kevva It sets zero by default

**Comment by shinnn** [comment]
> we could just set 755 for directories and 644 for files and then set `isFile()` and `isDirectory()` manually. It's ugly, but that'll do it I think.

At least it's better than leaving file mode `undefined`.

@TrySound If you really want to use [stat-mode](https://github.com/TooTallNate/stat-mode), you can use it *in your app*. I don't want decompress-unzip to extend default `fs.Stats` instance.

**Comment by TrySound** [comment]
It will not extend default stat. This module just set values to stat.mode
```js
if(file.contents) {
	new mode(file.stat).isFile(true)
} else {
	new mode(file.stat).isDirectory(true)
}
// file.stat.isFile() & file.stat.isDirectory() works correctly
```

**Comment by kevva** [comment]
@TrySound, we'll just set `file.stat.isDirectory() = file.stat.isDirectory() || function () { return true; };` inside the `if` statement [here](https://github.com/kevva/decompress-unzip/blob/master/index.js#L65), and the same inside [here](https://github.com/kevva/decompress-unzip/blob/master/index.js#L88) for files along with a default mode.

**Comment by TrySound** [comment]
So difficult to add one small and clean dependency?

**Comment by TrySound** [comment]
@kevva
>  @shinnn I don't want decompress-unzip to extend default fs.Stats instance.

**Comment by shinnn** [comment]
@TrySound Could you create a pull request to improve the code by using [stat-mode](https://github.com/TooTallNate/stat-mode)? We'll review it and judge it whether enough reasonable or not.

**Comment by TrySound** [comment]
@shinnn Sure
