### ISSUE TITLE
Default permission mode

### ISSUE THREAD

**Issue by TrySound** [kevva/decompress-unzip#8]
Need to add default permission mode for prevent files blocking
```js
var mode = new Mode(file.stat)
// 755
mode.owner.read = true;
mode.owner.write = true;
mode.owner.execute = true;
mode.group.read = true;
mode.group.execute = true;
mode.others.read = true;
mode.others.execute = true;
```

**Comment by TrySound** [comment]
@kevva @shinnn ASAP!

**Comment by kevva** [comment]
PR welcome.

**Comment by TrySound** [comment]
@kevva Will be soon after merge of PR to stat-mode :)

**Comment by kevva** [comment]
It's already merged :).

**Comment by TrySound** [comment]
@kevva  https://github.com/TooTallNate/stat-mode/pull/3
isFile and isDirectory rewrite permissions bits.

**Comment by shinnn** [comment]
@TrySound 

Just what @TooTallNate said in https://github.com/TooTallNate/stat-mode/issues/2#issuecomment-89736052. We are always confused by your insufficient explanation.

**Comment by TrySound** [comment]
@shinnn I explain everything here :)
https://github.com/TooTallNate/stat-mode/issues/2#issuecomment-89736258
_checkModeProperty method overwrites non-filetype bits with 0

**Comment by shinnn** [comment]
I mean we've been confused by your insufficient explanation *in various issues*.

You should read through this article before opening new issues. http://maddog.sitengine.ru/smart-question-ru.html

**Comment by TrySound** [comment]
@shinnn Okay. Thanks.
